The mask_account_card ok
The mask_account_card ok
The get_date ok
The get_date function returned an error.
Error: ValueError.
Inputs: ('11.05.2025',), {}
The filter_by_state ok
The sort_by_date ok
The sort_by_date function returned an error.
Error: TypeError.
Inputs: ([[{'id': 1, 'date': '2025-13-13T17:16:00.000000'}], [{'id': 2, 'date': '13.05.25'}], [{'id': 3, 'date': '2025-05-13T18:04:00+03:00'}], [{'id': 4, 'date': 'May 13 2025'}]],), {}
The get_mask_account function returned an error.
Error: ValueError.
Inputs: ('8990922113665229',), {}
The card_number_generator ok
The card_number_generator function returned an error.
Error: ValueError.
Inputs: (5, 4), {}
The card_number_generator function returned an error.
Error: ValueError.
Inputs: (5, 4), {}
The card_number_generator function returned an error.
Error: ValueError.
Inputs: (5, 4), {}
The card_number_generator function returned an error.
Error: ValueError.
Inputs: (5, 4), {}

The card_number_generator function returned an error.
Error: ValueError.
Inputs: (5, 4), {}

The card_number_generator function returned an error.
Error: ValueError.
Inputs: (5, 4), {}

The card_number_generator ok

The get_mask_card_number ok

The mask_account_card ok

The get_mask_card_number ok

The mask_account_card ok

The get_date ok

The get_date function returned an error.
Error: ValueError.
Inputs: ('11.05.2025',), {}

